Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from dipy.viz import regtools
from dipy.align.imaffine import (AffineMap,
                                 MutualInformationMetric,
                                 AffineRegistration)
from dipy.align.transforms import (TranslationTransform3D,
                                   RigidTransform3D,
                                   AffineTransform3D)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mviz[39;00m [38;5;28;01mimport[39;00m regtools
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01malign[39;00m[38;5;21;01m.[39;00m[38;5;21;01mimaffine[39;00m [38;5;28;01mimport[39;00m (AffineMap,
[1;32m      3[0m                                  MutualInformationMetric,
[1;32m      4[0m                                  AffineRegistration)
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01malign[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtransforms[39;00m [38;5;28;01mimport[39;00m (TranslationTransform3D,
[1;32m      6[0m                                    RigidTransform3D,
[1;32m      7[0m                                    AffineTransform3D)

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/dipy/viz/__init__.py:14[0m, in [0;36m<module>[0;34m[0m
[1;32m      6[0m fury, has_fury, _ [38;5;241m=[39m optional_package(
[1;32m      7[0m     [38;5;124m'[39m[38;5;124mfury[39m[38;5;124m'[39m,
[1;32m      8[0m     [38;5;124m"[39m[38;5;124mYou do not have FURY installed. Some visualization functions[39m[38;5;124m"[39m
[1;32m      9[0m     [38;5;124m"[39m[38;5;124mmight not work for you. For installation instructions, please visit: [39m[38;5;124m"[39m
[1;32m     10[0m     [38;5;124m"[39m[38;5;124mhttps://fury.gl/[39m[38;5;124m"[39m)
[1;32m     13[0m [38;5;28;01mif[39;00m has_fury:
[0;32m---> 14[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mfury[39;00m [38;5;28;01mimport[39;00m actor, window, colormap, lib
[1;32m     15[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mfury[39;00m [38;5;28;01mimport[39;00m interactor, ui, utils, shaders
[1;32m     16[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mfury[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m [38;5;28;01mimport[39;00m (fetch_viz_icons, read_viz_icons,
[1;32m     17[0m                            DATA_DIR [38;5;28;01mas[39;00m FURY_DATA_DIR)

[0;31mImportError[0m: cannot import name 'lib' from 'fury' (/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/fury/__init__.py)
ImportError: cannot import name 'lib' from 'fury' (/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/fury/__init__.py)

